# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: glow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-144.0.dev

dependencies:
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  genui: ^0.6.0
  genui_google_generative_ai: ^0.6.0
  go_router: ^17.0.0
  google_cloud_ai_generativelanguage_v1beta: ^0.3.0
  json_schema_builder: ^0.1.3
  logging: ^1.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  shaders:
    - shaders/orb_shader.frag
    - shaders/mesh_gradient.frag
    - shaders/ripple_frost.frag
